[package]
name = "problem84"
version = "0.1.0"
authors = ["kobayashi@kouei.co.jp <kobayashi@kouei.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6"
